import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Toaster, toast } from "sonner";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/Navbar";
import { Suspense } from "react";
import { SocketProvider } from "@/components/Providers/SocketProvider";
import { getUserAuth } from "@/lib/auth/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const { session } = await getUserAuth();

  if (!session) return;
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ClerkProvider>
            <SocketProvider userId={session?.user?.id}>
              <div className="flex">
                <Suspense
                  fallback={
                    <div className="text-5xl text-red-700">"ItsLoading"</div>
                  }
                >
                  <Navbar />
                  <main className="flex-1 mx-2 md:p-0 px-4 mt-4">
                    {children}
                  </main>
                </Suspense>
              </div>
            </SocketProvider>
          </ClerkProvider>
          <Toaster richColors position="bottom-center" />
        </ThemeProvider>
      </body>
    </html>
  );
}
